### ISSUE TITLE
Include representation for edges not associated to a transition system

### ISSUE THREAD

**Issue by fesemeyer** [leonbohn/lama#59]
The trait `IsEdge` should be implemented for everything that represents an edge. At the moment, there is no way to represent an edge that is not associated to a specific transition system. This is a problem because paths are not associated to transition systems and we therefore cannot extract edges from paths.

**Comment by leonbohn** [comment]
This is indeed a problem, but unfortunately one that will be more difficult to solve. At the moment, we have the trait `IsEdge<'ts, E, Idx, C>` where `'ts` is a lifetime associated with the transition system that the edge is coming from. If we now implement `IsEdge<'a, E, Idx, C>` for a tuple `(Idx, E, C, Idx)`, then we would somehow need to return a reference `&'a E` in the `expression` method. But we only have the lifetime of the tuple (`'0 self`) available, which can unfortunately not be used to give us a reference `&'a E`.

Therefore this change would make it necessary to somehow rework the `IsEdge` trait. There are essentially two options:
1. split the whole thing up so that we have one trait `IdentifiesEdge`, which is implemented by everything that resembles an edge, whether it is from a transition system (so with a borrowed expression) or not (if it is just a tuple of elements)
2. change the signature of the `expression` method and no longer return something with a specific lifetime `'a`. This would also allow removing the lifetime from the definition of the `IsEdge` trait.

If we go with option 2, then we need to be careful as it is not possible to simply return a reference to the expression with the same lifetime as `self`. I already tried this at some point and ran into problems downstream. It might however be possible to change the signature of the `expression` method to return an `impl Borrow<E>` or something similar.
